services:
  onesh3d-api:
    build: ./api
    env_file: ./api/.env
    restart: unless-stopped
    environment:
      - DOCKER=true
    volumes:
      - ./api_storage:/storage

        
    ports:
      - "3862:3862"
    networks:
      - oneshot3d-web

  onesh3d-web:
    build: 
      context: ./web
      args:
        - PUBLIC_API_URL=https://oneshot3d-game.com/api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      
    ports:
      - "4321:4321"
    depends_on:
      - onesh3d-api
    networks:
      - oneshot3d-web

networks:
  oneshot3d-web:
    driver: bridge